### GET root
GET {{host}}
Accept: application/json

### GET extract
GET {{host}}/clientes/1/extrato

### POST credit transaction
POST {{host}}/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1000,
  "tipo" : "c",
  "descricao" : "descricao"
}


### POST debit transaction
POST {{host}}/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1999,
  "tipo" : "d",
  "descricao" : "descricao"
}

### POST credit transaction
POST https://localhost:7195/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1000,
  "tipo" : "c",
  "descricao" : "descricao"
}

### POST credit transaction
POST https://localhost:7196/clientes/1/transacoes
Content-Type: application/json

{
  "valor": 1000,
  "tipo" : "c",
  "descricao" : "descricao"
}